[package]
name = "automerge-cli"
version = "0.1.0"
authors = ["Alex Good <alex@memoryandthought.me>"]
edition = "2018"

[[bin]]
name = "automerge"
path = "src/main.rs"

[dependencies]
clap = "3.0.0-beta.1"
automerge-backend = { path = "../automerge-backend" }
automerge-frontend = { path = "../automerge-frontend" }
automerge-protocol = { path = "../automerge-protocol" }
serde_json = "^1.0"
