[package]
name = "automerge"
version = "0.0.2"
authors = ["Alex Good <alex@memoryandthought.me>"]
edition = "2018"
license = "MIT"
homepage = "https://github.com/alexjg/automerge-rs"
repository = "https://github.com/alexjg/automerge-rs"
categories = ["data-structures"]
description = "Rust implementation of the Automerge replicated JSON datatype"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "automerge"

[dependencies]
serde = { version = "^1.0", features=["derive"] }
serde_json = "^1.0"
uuid = { version = "^0.8.2", features=["v4"] }
automerge-backend = { path = "../automerge-backend" }
automerge-frontend = { path = "../automerge-frontend" }
automerge-protocol = { path = "../automerge-protocol" }

[dev-dependencies]
criterion = "0.3.3"
hex = "0.4.3"
pretty_assertions = "0.7.1"
rand = "0.8.2"
test-env-log = { version = "0.2.6", features = ["trace"], default-features = false }
env_logger = "*"
tracing = "0.1.25"
tracing-subscriber = {version = "0.2", features = ["chrono", "env-filter", "fmt"]}

[[bench]]
name = "crdt_benchmarks"
harness = false
